import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {JSDOM} from 'jsdom';
import {metaReview} from '../assets/blended/meta-review.js';import {shift} from '../assets/blended/metrics.js';
const read=p=>JSON.parse(fs.readFileSync(new URL('../'+p,import.meta.url)));
const data={returns:read('data/returns.json'),...Object.fromEntries(['shopify','meta','google','creators'].map(k=>[k,read('data/'+k+'.json')]))},costs=read('assets/blended/costs.json');
const source=fs.readFileSync(new URL('../assets/blended/meta-review-app.js',import.meta.url),'utf8').replace(/^import[^\n]*\n/gm,'');
async function view(mode='meta'){
 const dom=new JSDOM(`<body data-review-mode="${mode}"><div id="reviewPicker"></div><main id="reviewApp"></main><footer id="reviewSource"></footer>`,{url:'https://cijfers.lumeworks.nl/meta-test?from=2026-09-01&to=2026-09-30',runScripts:'outside-only'});
 Object.assign(dom.window,{load:async()=>({data:structuredClone(data),costs:structuredClone(costs),errors:{}}),metaReview,shift,createDatePicker:o=>{dom.picker=o;return {update(){},close(){}};}});dom.window.eval(source);await new Promise(setImmediate);return dom;
}
test('Meta and total store lines are additive, and the last visible line cannot be removed',async()=>{const d=await view(),w=d.window,doc=w.document;const inputs=[...doc.querySelectorAll('[data-line]')];assert.equal(inputs.filter(x=>x.checked).length,2);const store=inputs.find(x=>x.dataset.line==='storeScenario');store.checked=true;store.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(inputs.filter(x=>x.checked).length,3);assert.equal(doc.querySelectorAll('.review-chart path').length,3);for(const i of inputs.filter(x=>x.checked)){i.checked=false;i.dispatchEvent(new w.Event('change',{bubbles:true}));}assert.equal(inputs.filter(x=>x.checked).length,1);d.window.close();});
test('date selection is constrained and keyboard selection resolves an actual day',async()=>{const d=await view('daan'),w=d.window,doc=w.document;assert.equal(d.picker.min,'2026-08-05');const before=w.location.href;d.picker.onApply('2026-08-04','2026-09-30');assert.equal(w.location.href,before);const point=doc.querySelector('[data-day]');point.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert(doc.getElementById('reviewDay').textContent.includes('sep'));assert(doc.getElementById('reviewApp').textContent.includes('Negatieve dagen tellen mee'));assert(doc.getElementById('reviewApp').textContent.includes('excl. btw'));d.window.close();});
test('scenario fee does not persist any financial payload or change the underlying cost register',async()=>{const d=await view(),w=d.window,doc=w.document;const select=doc.getElementById('reviewMonthly');select.value='500';select.dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(new URL(w.location.href).searchParams.get('monthly'),'500');assert.equal(costs.meta_management.monthly_fixed,1500);assert.equal(w.localStorage.length,0);assert.equal(w.sessionStorage.length,0);assert(doc.getElementById('reviewApp').textContent.includes('worden niet opgeslagen'));d.window.close();});
